version: '3'

services:
  # Generate certificates only valid for 14 days.
  cert:
    build: ./cert
    volumes:
      - cert:/cert

  # Generate a fragmented MP4 file for testing.
  media:
    build: ./media
    volumes:
      - media:/media

  # Serve the web code once we have certificates.
  web:
    build: ./web
    ports:
      - "4444:4444"
    volumes:
      - cert:/cert
    depends_on:
      cert:
        condition: service_completed_successfully

  # Run the server once we have certificates and media.
  server:
    build: ./server
    environment:
      - RUST_LOG=debug
    ports:
      - "4443:4443/udp"
    volumes:
      - cert:/cert
      - media:/media
    depends_on:
      cert:
        condition: service_completed_successfully
      media:
        condition: service_completed_successfully

volumes:
  cert:
  media:
