services:
  redis:
    image: redis:7
    container_name: moq-redis
    ports:
      - "6379"

  api:
    build: .
    container_name: moq-api
    environment:
      RUST_LOG: ${RUST_LOG:-debug}
    entrypoint: moq-api
    command: --redis redis://redis:6379
    ports:
      - "80"

  relay:
    build: .
    container_name: moq-relay
    environment:
      RUST_LOG: ${RUST_LOG:-debug}
    entrypoint: moq-relay
    command: --tls-cert /tmp/relay-server.crt --tls-key /tmp/relay-server.key --tls-disable-verify --api http://api --node https://relay --dev --announce https://dir
    depends_on:
      - api
      - dir
    ports:
      - "4443:443"
      - "4443:443/udp"

  dir:
    build: .
    container_name: moq-dir
    environment:
      RUST_LOG: ${RUST_LOG:-debug}
    entrypoint: moq-dir
    command: --tls-cert /tmp/relay-server.crt --tls-key /tmp/relay-server.key
    ports:
      - "443/udp"

  pub:
    build: .
    container_name: moq-pub
    environment:
      RUST_LOG: ${RUST_LOG:-debug}
      HOST: relay
      PORT: 443
      ADDR: relay:443
      SCHEME: https
      NAME: bbb
      URL: https://relay:443
    depends_on:
      - relay

  sub:
    build: .
    container_name: moq-sub
    environment:
      RUST_LOG: ${RUST_LOG:-debug}
      HOST: relay
      PORT: 443
      ADDR: relay:443
      NAME: bbb
      URL: https://relay:443/bbb
    depends_on:
      - pub
