#!/bin/bash
set -euo pipefail

# Use debug logging by default
export RUST_LOG="${RUST_LOG:-debug}"

# Connect to relay1 by default.
HOST="${HOST:-relay1}"
PORT="${PORT:-443}"
ADDR="${ADDR:-$HOST:$PORT}"

# Use the broadcast name "bbb" by default
NAME="${NAME:-bbb}"

# Combine the host and name into a URL.
URL="${URL:-"https://$ADDR/$NAME"}"

moq-sub --name "$NAME" "$URL" | ffplay -
