name: server

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy, rustfmt

    - name: test
      working-directory: server
      run: cargo test --verbose

    - name: fmt
      uses: mbrobbel/rustfmt-check@master
      working-directory: server
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: clippy
      uses: actions-rs/clippy-check@v1
      working-directory: server
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
