name: web

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install
      working-directory: web
      run: yarn install

    - name: cert
      working-directory: cert
      run: ./generate

    - name: build
      working-directory: web
      run: yarn build

    - name: fmt
      working-directory: web
      run: yarn prettier --check .

    - name: lint
      working-directory: web
      run: yarn lint
