name: Web

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install
      working-directory: web
      run: yarn install
    - name: Cert
      working-directory: cert
      run: ./generate
    - name: Build
      working-directory: web
      run: yarn build
    - name: Lint
      working-directory: web
      run: yarn lint
